services:
  traefik:
    image: traefik
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/etc/traefik/config.yml"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./etc/network/traefik/config.yml:/etc/traefik/config.yml:ro
      - ./etc/network/.certificates:/etc/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - charmomics-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=charmomics-network"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.rule=Host(`localhost`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

  backend:
    build:
      context: ./backend/
      target: development-stage
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    networks:
      - charmomics-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=charmomics-network"
      - "traefik.http.routers.backend-charmomics-router.tls=true"
      - "traefik.http.routers.backend-charmomics-router.rule=Host(`local.charmomics.cgds`)"
      - "traefik.http.routers.backend-charmomics-router.rule=PathPrefix(`/charmomics/api`)"
      - "traefik.http.routers.backend-charmomics-router.service=backend-charmomics-api-service"
      - "traefik.http.routers.backend-charmomics-router.middlewares=backend-charmomics-strip-prefix"
      - "traefik.http.middlewares.backend-charmomics-strip-prefix.stripprefix.prefixes=/charmomics/api"
      - "traefik.http.services.backend-charmomics-api-service.loadbalancer.server.port=8000"

  charmomics-db:
    image: mongo:8.0.3
    volumes:
      - ./etc/fixtures/initial-seed/initial-db-seed.sh:/docker-entrypoint-initdb.d/initial-db-seed.sh
      - ./etc/fixtures/:/tmp/fixtures
    ports:
      - 27017:27017
    networks:
      - charmomics-network
    environment:
      MONGO_INITDB_DATABASE: charmomics_db

networks:
  charmomics-network:
    name: charmomics-network
