services:
  traefik:
    image: traefik
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - charmomics-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=charmomics-network"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

  frontend:
    build:
      context: ./frontend/
      target: development-stage
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src
    networks:
      - charmomics-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=charmomics-network"
      - "traefik.http.routers.frontend-charmomics-router.rule=Host(`localhost`)"
      - "traefik.http.routers.frontend-charmomics-router.service=frontend-charmomics-web-service"
      - "traefik.http.services.frontend-charmomics-web-service.loadbalancer.server.port=80"

  backend:
    build:
      context: ./backend/
      target: development-stage
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    networks:
      - charmomics-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=charmomics-network"
      - "traefik.http.routers.backend-charmomics-router.rule=Host(`localhost`)"
      - "traefik.http.routers.backend-charmomics-router.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.backend-charmomics-router.service=backend-charmomics-api-service"
      - "traefik.http.routers.backend-charmomics-router.middlewares=backend-charmomics-strip-prefix"
      - "traefik.http.middlewares.backend-charmomics-strip-prefix.stripprefix.prefixes=/api"
      - "traefik.http.services.backend-charmomics-api-service.loadbalancer.server.port=8000"

  charmomics-db:
    image: mongo:8.0.3
    volumes:
      - ./etc/fixtures/initial-seed/initial-db-seed.sh:/docker-entrypoint-initdb.d/initial-db-seed.sh
      - ./etc/fixtures/:/tmp/fixtures
    ports:
      - 27017:27017
    networks:
      - charmomics-network
    environment:
      MONGO_INITDB_DATABASE: charmomics_db

networks:
  charmomics-network:
    name: charmomics-network
