services:
  traefik:
    image: traefik
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - franklin-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=franklin-network"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

  frontend:
    build:
      context: ./frontend/
      target: development-stage
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src
    networks:
      - franklin-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=franklin-network"
      - "traefik.http.routers.frontend-franklin-router.rule=Host(`localhost`)"
      - "traefik.http.routers.frontend-franklin-router.service=frontend-franklin-web-service"
      - "traefik.http.services.frontend-franklin-web-service.loadbalancer.server.port=80"

  backend:
    build:
      context: ./backend/
      target: development-stage
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    networks:
      - franklin-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=franklin-network"
      - "traefik.http.routers.backend-franklin-router.rule=Host(`localhost`)"
      - "traefik.http.routers.backend-franklin-router.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.backend-franklin-router.service=backend-franklin-api-service"
      - "traefik.http.routers.backend-franklin-router.middlewares=backend-franklin-strip-prefix"
      - "traefik.http.middlewares.backend-franklin-strip-prefix.stripprefix.prefixes=/api"
      - "traefik.http.services.backend-franklin-api-service.loadbalancer.server.port=8000"

  franklin-db:
    image: mongo:8.0.3
    ports:
      - 27017:27017
    networks:
      - franklin-network
    environment:
      MONGO_INITDB_DATABASE: franklin_db


networks:
  franklin-network:
    name: franklin-network
