#!/bin/bash
#
#SBATCH --job-name=ditto_generate_statistics
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=96G
#SBATCH --partition=short
#SBATCH --time=3:00:00
#SBATCH --output=%x_%j.out
#SBATCH --error=%x_%j.err
#SBATCH --array=0-23

ARGS=(1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X Y)

ml Anaconda3
conda activate charmomics
python3 src/filter_scores.py -d ~/Documents/ditto/genes -chr ${ARGS[$SLURM_ARRAY_TASK_ID]} -o ~/Documents/ditto/genes/filtered