#!/bin/bash
#
#SBATCH --job-name=ditto_bgzip_tabix
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --mem=8G
#SBATCH --partition=short
#SBATCH --time=3:00:00
#SBATCH --output=%x_%j.out
#SBATCH --error=%x_%j.err
#SBATCH --array=0-23

ARGS=(1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X Y)

ml Anaconda3
conda activate bcftools
./bgzip_tsv.sh ${ARGS[$SLURM_ARRAY_TASK_ID]}
